/**
 * Becarefull the appName Value has to be the same as the key object value
 */

export default {
  Projects: {
    appName: 'Projects',
    title: 'Project Manager',
    fullSize: false,
    display: false,
    zIndex: 0,
    icon: 'fas fa-sitemap fa-2x',
    reduce: false,
    typeUser: ['all'],
  },
  Chat: {
    appName: 'Chat',
    title: 'Chat',
    fullSize: false,
    display: false,
    reduce: false,
    zIndex: 0,
    icon: 'far fa-comments fa-2x',
    typeUser: ['all'],
  },
  Settings: {
    appName: 'Settings',
    title: 'Settings',
    fullSize: false,
    display: false,
    zIndex: 0,
    icon: 'fas fa-cog fa-2x',
    reduce: false,
    typeUser: ['all'],
  },
  TextEditor: {
    appName: 'TextEditor',
    title: 'Text Editor',
    fullSize: false,
    display: false,
    zIndex: 0,
    icon: 'fas fa-edit fa-2x',
    reduce: false,
    typeUser: ['all'],
  },
  Task: {
    appName: 'Task',
    title: 'Task Manager',
    fullSize: false,
    display: false,
    zIndex: 0,
    icon: 'fas fa-tasks fa-2x',
    reduce: false,
    typeUser: ['student'],
  },
  AddressBook: {
    appName: 'AddressBook',
    title: 'AddressBook',
    fullSize: false,
    display: false,
    zIndex: 0,
    icon: 'far fa-address-book fa-2x',
    reduce: false,
    typeUser: ['all'],
  },
};
